I looked at the Firebase Cloud Function logs and the error you're getting is because you're not passing the "account" property in the request header. The API of this application requires that an account property be passed in the request header on every call:
Error: No account info was passed as a token in the Authorization header. Make sure you authorize your request by providing the following HTTP header: location: <Location>
    at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:133:19)
    at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:120:11)
    at /workspace/controllers/assignmentsGen2.js:53:22
    at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)
    at next (/workspace/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/workspace/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)
    at /workspace/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/workspace/node_modules/express/lib/router/ind